sudo: required
language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

# services:
#  - docker

script:
 - dotnet restore src/Core/DocumentDb.Fluent.csproj
 - dotnet build src/Core/DocumentDb.Fluent.csproj
